name: "AirSend Enhanced"
description: "AirSend Web Service with bidirectional reception (local connection, no internet, no cloud)"
version: "2.0"
slug: "airsend"
url: https://github.com/devmel/hass_airsend-addon
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
startup: services
init: false
hassio_api: true
hassio_role: default
ports:
  33863/tcp: 33863
ports_description:
  33863/tcp: AirSend WebService and Reception webhook endpoint
options:
  auto_include: true
  reception_enabled: true
  log_level: "INFO"
  health_check_interval: 60
  max_retries: 5
schema:
  auto_include: bool
  reception_enabled: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  health_check_interval: "int(30,300)"
  max_retries: "int(1,10)"
map:
  - config:rw
  - share:rw
environment:
  RECEPTION_ENABLED: true
  DEBUG: 0
  LOG_LEVEL: INFO